SELECT
  *
FROM
  "BRIGHT_COFFEE"."COFFEE_SCHEME"."TABLE_2"
LIMIT
  10;
  
  SELECT MIN (TRANSACTION_TIME)
  FROM"BRIGHT_COFFEE"."COFFEE_SCHEME"."TABLE_2";

  SELECT MAX (TRANSACTION_TIME)
  FROM"BRIGHT_COFFEE"."COFFEE_SCHEME"."TABLE_2";

  SELECT TRANSACTION_DATE,
TO_CHAR(TO_DATE(TRANSACTION_DATE, 'YYYY/MM/DD'),'YYYYMM') AS MONTH_ID,
COUNT (TRANSACTION_ID) NUMBER_OF_SALES,
COUNT(PRODUCT_ID) AS UNIQUE_PRODCUTS_SOLD,
SUM( TRANSACTION_QTY* TO_NUMBER(REPLACE(UNIT_PRICE, ',', ','))) TOTAL_AMOUNT,
PRODUCT_CATEGORY,
PRODUCT_DETAIL,
PRODUCT_TYPE,
STORE_LOCATION,
CASE
WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '16:59:59' THEN 'AFTERNOON'
WHEN TRANSACTION_TIME BETWEEN '17:00:00' AND '19:59:59' THEN 'EVENING'
ELSE 'NIGHT'
END AS TIME_BUCKETS
FROM "BRIGHT_COFFEE"."COFFEE_SCHEME"."TABLE_2"
GROUP BY ALL
ORDER BY TRANSACTION_DATE ASC; 